"""
sr_probe.py — Stanley-Reisner / homological probe for Frankl's union-closed
conjecture.  Lives under math/ideas/generation/ (idea-generation only).

GOAL.  Test whether a *labelling-sensitive* homological invariant of a complex
built from a union-closed family F correlates with / lower-bounds the abundance
max_x freq(x)/|F|.  The cone obstruction (lattice_attack.md sec.4) kills every
invariant of the ABSTRACT lattice L=(F,union).  So we deliberately build complexes
on the GROUND SET [n] (the labelling F.2 data), not on the poset L.

We compute, per UC family F (with emptyset adjoined) over n<=5:

  (A) order complex of L : reduced Euler characteristic = Mobius(0,1) of Lhat.
      [control: this is a poset/cone invariant, expected DEAD under coning]

  (B) the "non-cover complex" NC(F): simplicial complex on vertex set [n] whose
      faces are the subsets S<=[n] that are CONTAINED in some member of F
      (i.e. S is a face iff S subset of A for some A in F).  This is the order
      ideal generated by F in 2^[n] -- a genuine simplicial complex on [n].
      Its Stanley-Reisner ring k[NC] is the object of Hochster/Reisner/EagonReiner.
      Under the cone G -> cone(G) (adjoin fresh z to every nonempty set), NC(cone)
      is the TOPOLOGICAL CONE z * NC'(G) and z is exactly the abundant vertex.

  (C) Hochster data: for the Alexander dual NC(F)^vee, projective dimension of
      k[NC] = reg(I_{NC^vee}) (Eagon-Reiner).  We instead directly compute the
      reduced homology Betti numbers of induced subcomplexes (Hochster) and the
      total Betti number, plus per-vertex "link contractibility" (cone test).

  (D) cone-vertex test: a vertex x of a complex Delta is a CONE APEX iff
      every facet contains x iff link(x)=del(x) iff x in every maximal face.
      For NC(F), x is an apex iff x in every maximal member of F.  We compare
      "x is an apex of NC(F)" and softer homological notions to abundance.

Output: a JSONL row per family + a summary with candidate inequalities.

Run:  python3 sr_probe.py 5
"""
from __future__ import annotations
import sys, os, json, itertools
from functools import lru_cache

# reuse the project's enumerator / family tools
HERE = os.path.dirname(os.path.abspath(__file__))
EXP = os.path.normpath(os.path.join(HERE, "..", "..", "frankl", "experiments"))
sys.path.insert(0, EXP)

from enumerate import all_uc_families  # noqa: E402
from uc_family import frequencies, ground_set  # noqa: E402


# ----------------------------------------------------------------------------
# basic homology over Q (rational) by rank of boundary maps (Smith-free: use
# numeric rank via fraction-free Gaussian elimination on small integer matrices)
# ----------------------------------------------------------------------------

def _rank_mod_p(rows, p=1000003):
    """Rank of an integer matrix mod a large prime (fast, faithful for small,
    sparse, small-entry matrices we generate). Returns integer rank."""
    M = [list(r) for r in rows]
    if not M:
        return 0
    ncol = len(M[0]) if M else 0
    rank = 0
    col = 0
    nrow = len(M)
    r = 0
    while r < nrow and col < ncol:
        piv = None
        for i in range(r, nrow):
            if M[i][col] % p != 0:
                piv = i
                break
        if piv is None:
            col += 1
            continue
        M[r], M[piv] = M[piv], M[r]
        inv = pow(M[r][col] % p, p - 2, p)
        M[r] = [(v * inv) % p for v in M[r]]
        for i in range(nrow):
            if i != r and M[i][col] % p != 0:
                f = M[i][col] % p
                M[i] = [(a - f * b) % p for a, b in zip(M[i], M[r])]
        r += 1
        rank += 1
        col += 1
    return rank


def reduced_homology_ranks(faces):
    """Given a simplicial complex as a set of faces (each a frozenset of vertex
    ints), INCLUDING the empty face for reduced homology, return the list of
    reduced Betti numbers [b_{-1}, b_0, b_1, ...] over F_p.

    Uses augmented chain complex (reduced homology).  Faces must be downward
    closed (a simplicial complex)."""
    # group faces by dimension (dim = |face|-1). include empty face (dim -1).
    by_dim = {}
    for f in faces:
        d = len(f) - 1
        by_dim.setdefault(d, []).append(tuple(sorted(f)))
    if not by_dim:
        return []
    maxd = max(by_dim)
    # ensure empty face present for reduced homology
    by_dim.setdefault(-1, [tuple()])
    for d in by_dim:
        by_dim[d].sort()
    index = {d: {f: i for i, f in enumerate(by_dim[d])} for d in by_dim}
    # boundary map d_k : C_k -> C_{k-1}
    ranks = {}
    for k in range(0, maxd + 1):
        if k not in by_dim or (k - 1) not in by_dim:
            ranks[k] = 0
            continue
        rows = []  # one row per (k-1)-face, columns per k-face -> but rank is same transposed
        kfaces = by_dim[k]
        km1 = index[k - 1]
        mat = []
        for f in kfaces:
            col = [0] * len(km1)
            for j in range(len(f)):
                face = f[:j] + f[j + 1:]
                sign = -1 if (j % 2) else 1
                col[km1[face]] += sign
            mat.append(col)  # row = this k-face's boundary in C_{k-1}
        ranks[k] = _rank_mod_p(mat)
    # reduced betti: b_k = dim C_k - rank d_k - rank d_{k+1}
    betti = []
    for k in range(-1, maxd + 1):
        ck = len(by_dim.get(k, []))
        rk = ranks.get(k, 0)          # rank of d_k : C_k -> C_{k-1}
        rk1 = ranks.get(k + 1, 0)     # rank of d_{k+1}: C_{k+1} -> C_k
        betti.append(ck - rk - rk1)
    return betti


# ----------------------------------------------------------------------------
# complexes built from a UC family
# ----------------------------------------------------------------------------

def order_ideal_faces(masks, n):
    """NC(F): all subsets of [n] contained in some member of F, as frozensets.
    Downward closed simplicial complex on [n]. Includes empty face."""
    faces = set()
    faces.add(frozenset())
    for m in masks:
        elts = [i for i in range(n) if (m >> i) & 1]
        # add all subsets of elts -- but only need to add m's subsets; do via
        # generating subsets of the maximal members for efficiency
        for r in range(len(elts) + 1):
            for c in itertools.combinations(elts, r):
                faces.add(frozenset(c))
    return faces


def maximal_members(masks):
    ms = list(masks)
    maxs = []
    for a in ms:
        if a == 0:
            continue
        if not any(a != b and (a & b) == a for b in ms):  # a subset of b, a!=b
            maxs.append(a)
    return maxs


def order_complex_of_lattice_euler(masks):
    """Reduced Euler characteristic of the order complex of the OPEN interval
    (0hat,1hat) of Lhat = L (which already has 0hat=emptyset) with 1hat=top
    adjoined if needed.  Equivalently Mobius(0hat,1hat).  Control invariant."""
    # L = masks (assume emptyset in masks as 0hat). top = union of all.
    L = sorted(set(masks))
    if 0 not in L:
        L = [0] + L
    top = 0
    for m in L:
        top |= m
    if top not in L:
        L = L + [top]
    # proper part P = L \ {0, top}
    P = [m for m in L if m != 0 and m != top]
    # order complex: chains in P. reduced Euler char = sum (-1)^(|chain|-1)
    # = Mobius(0,top) by Philip Hall.  Compute Mobius directly.
    Lset = sorted(set(L))
    @lru_cache(maxsize=None)
    def mob(a, b):
        if a == b:
            return 1
        # sum over a<=z<b of mob(a,z), negated
        s = 0
        for z in Lset:
            if z == b:
                continue
            if (a & z) == a and (z & b) == z and z != b:  # a<=z<b
                if z == a or (a & z) == a:
                    if (z & b) == z and z != b and (a & z) == a:
                        s += mob(a, z)
        return -s
    return mob(0, top)


# ----------------------------------------------------------------------------
# the homological "cone apex" notions
# ----------------------------------------------------------------------------

def apex_vertices(masks, n):
    """Vertices x of NC(F) that are CONE APEXES: x lies in every maximal member.
    If NC(F) has a cone apex x then NC(F) is contractible with apex x, and x is
    an abundant element candidate."""
    maxs = maximal_members(masks)
    if not maxs:
        return []
    out = []
    for x in range(n):
        bit = 1 << x
        if all(m & bit for m in maxs):
            out.append(x)
    return out


def main(nmax):
    rows = []
    n_fail_apex = 0
    n_fam = 0
    # candidate-inequality trackers
    worst_apex_abund = 1.0
    worst_reg_minus = None
    cone_dead_check = []  # (euler) distribution
    nonflat_cube = {}

    for n in range(0, nmax + 1):
        for F in all_uc_families(n):
            if not F:
                continue
            masks = set(F)
            masks.add(0)  # adjoin emptyset (bottom). F.2 convention.
            nn = ground_set(frozenset(masks))
            if nn == 0:
                continue
            freqs = frequencies(list(masks), nn)
            sizeF = len(masks)
            abund = max(freqs) / sizeF
            n_fam += 1

            # (B) order ideal complex NC(F) on [nn]
            faces = order_ideal_faces(masks, nn)
            betti = reduced_homology_ranks(faces)
            total_betti = sum(abs(b) for b in betti)
            reduced_euler = sum(((-1) ** (k - 1)) * b
                                for k, b in zip(range(-1, len(betti) - 1), betti))

            # (D) cone apex vertices of NC(F)
            apex = apex_vertices(masks, nn)
            apex_freqs = [freqs[x] for x in apex]
            apex_abund = (max(apex_freqs) / sizeF) if apex else None

            # the candidate claim: if NC(F) has a cone apex, abundance>=1/2?
            if apex:
                # apex vertex is in every maximal member, so freq(apex) is large
                a_ab = max(apex_freqs) / sizeF
                worst_apex_abund = min(worst_apex_abund, a_ab)

            # (A) control: order complex euler (mobius)
            try:
                eul = order_complex_of_lattice_euler(masks)
            except Exception:
                eul = None

            rows.append({
                "n": nn, "sizeF": sizeF, "abund": abund,
                "betti": betti, "total_betti": total_betti,
                "reduced_euler": reduced_euler,
                "n_apex": len(apex), "apex_abund": apex_abund,
                "mobius_orderL": eul,
                "freqs": sorted(freqs, reverse=True),
            })

    return rows, {
        "n_fam": n_fam,
        "worst_apex_abund": worst_apex_abund,
    }


if __name__ == "__main__":
    nmax = int(sys.argv[1]) if len(sys.argv) > 1 else 4
    rows, summ = main(nmax)
    outdir = HERE
    with open(os.path.join(outdir, f"sr_probe_n{nmax}.jsonl"), "w") as fh:
        for r in rows:
            fh.write(json.dumps(r) + "\n")
    # ---- analysis ----
    import statistics
    print(f"families (with emptyset, nonempty ground): {summ['n_fam']}")
    # Claim 1: NC(F) cone-apex => abundance >= 1/2  (and apex itself abundant)
    have_apex = [r for r in rows if r["n_apex"] > 0]
    no_apex = [r for r in rows if r["n_apex"] == 0]
    print(f"families with a cone-apex vertex in NC(F): {len(have_apex)}")
    print(f"families with NO cone-apex vertex:         {len(no_apex)}")
    if have_apex:
        wa = min(r["apex_abund"] for r in have_apex)
        print(f"  min abundance of an apex vertex: {wa:.4f}  "
              f"(claim: apex is always >= 1/2? {wa >= 0.5})")
    if no_apex:
        wn = min(r["abund"] for r in no_apex)
        print(f"  min abundance among NO-apex families: {wn:.4f}")
        # are no-apex families still Frankl? yes by global result; but is there
        # a homological certificate for THEM?
    # Claim 2 (control): is reduced_euler / total_betti FLAT on cubes?
    cubes = [r for r in rows if r["sizeF"] in (2, 4, 8, 16, 32)
             and r["abund"] == 0.5 and len(set(r["freqs"])) == 1]
    print("\nCube-like (flat-freq, abund .5) families homology:")
    for r in sorted(cubes, key=lambda r: r["sizeF"]):
        print(f"  |F|={r['sizeF']:2d} n={r['n']} betti={r['betti']} "
              f"euler={r['reduced_euler']} totbetti={r['total_betti']} "
              f"n_apex={r['n_apex']}")
    # Claim 3: does total_betti or reduced_euler separate abund<.55 from >=.55?
    print("\nCorrelation total_betti vs abundance:")
    lo = [r["total_betti"] for r in rows if r["abund"] < 0.55]
    hi = [r["total_betti"] for r in rows if r["abund"] >= 0.55]
    if lo and hi:
        print(f"  abund<.55: total_betti mean {statistics.mean(lo):.3f} "
              f"max {max(lo)} ; abund>=.55: mean {statistics.mean(hi):.3f} "
              f"max {max(hi)}")
